---
name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: 代码检查
        run: pnpm run lint
      - name: 单元测试
        run: pnpm run test
      - name: 构建应用
        run: pnpm run build
