on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        with:
          # 这里必须指定 pnpm 版本，按照 https://github.com/pnpm/action-setup?tab=readme-ov-file 的说法，
          # Optional when there is a packageManager field in the package.json
          version: 9.15.2
  lint:
    needs: [ install ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build



